- hw0/qwe854896/countline.py
---
- [O] A clear title
- [O] A meaningful message for PR, as well as its commits
- [O] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [O] excluding any irrelevant files, such as binaries, text files, or dot files
> hw0 submit by qwe854896

- hw0/BillyNI-OUO/countline.py
- add countline.py in /BillyNI-OUO/
- pass the validate.sh
---
> hw0 submit by BillyNI-OUO

- hw0/darrenleeleelee1/countline.py
> hw0 submit by darrenleeleelee1

- hw0/looksgreat/countline.py
> hw0 submit by looksgreat

- hw0/jamie212/countline.py
> jamie212 hw0 attempt 2

- hw0/ksh2027/countline.py
> ksh2027_hw0_submit

- hw0/huroy5518/countline.py
> huroy5518 hw0 attempt1

- hw0/mmi366127/countline.py
> add countline.py

- hw1/huroy5518/countline.py
- hw1/huroy5518/countline.sh
> huroy5518 hw1 attempt1

- hw1/mmi366127/countline.py
- hw1/mmi366127/countline.sh
> Mmi366127 hw1 attempt1

- hw1/qwe854896/countline.py
- hw1/qwe854896/countline.sh
> hw1 submit by qwe854896

- hw1/tychuang1211/countline.py
- hw1/tychuang1211/countline.sh
1. Use bash to reimplement `countline.py` as `countline.sh`
2. Modify the script `countline.py` so that it reads the environment variable named "PYTHON_BIN" to switch the Python executable for the script.
---
> hw1 submit by tychuang1211

- hw1/XDEv11/countline.py
- hw1/XDEv11/countline.sh
> Finish hw1

- hw1/ksh2027/countline.py
- hw1/ksh2027/countline.sh
> hw1 submit by ksh2027

- hw1/henry0928/countline.py
- hw1/henry0928/countline.sh
> henry0928-hw1-attemp1

- hw1/yoyojs200602/countline.py
- hw1/yoyojs200602/countline.sh
> Yoyojs200602 hw1 attempt1

- hw1/B10732009/countline.py
- hw1/B10732009/countline.sh
> B10732009 hw1 attempt1

- hw1/Calvin9c/countline.py
- hw1/Calvin9c/countline.sh
> Calvin9c hw1 attempt1

- hw1/darrenleeleelee1/countline.py
- hw1/darrenleeleelee1/countline.sh
> hw1 submit by darrenleeleelee1

- hw1/countline.py
- hw1/jamie212/countline.py
- hw1/jamie212/countline.sh
> Jamie212 hw1 attempt1

- hw2/huroy5518/q1/Makefile
- hw2/huroy5518/q1/line.cpp
- hw2/huroy5518/q1/line.hpp
- hw2/huroy5518/q1/main.cpp
- hw2/huroy5518/q2/Makefile
- hw2/huroy5518/q2/angle_test.py
- hw2/huroy5518/q2/main.cpp
> huroy5518 hw2 attempt2

- hw2/Yojahuang/q1/Line.cpp
- hw2/Yojahuang/q1/Line.h
- hw2/Yojahuang/q1/Makefile
- hw2/Yojahuang/q1/main.cpp
- hw2/Yojahuang/q2/Makefile
- hw2/Yojahuang/q2/getAngle.cpp
- hw2/Yojahuang/q2/getAngle_test.py
> Yojahuang hw2 attempt1

- hw2/qwe854896/q1/Line.cpp
- hw2/qwe854896/q1/Line.h
- hw2/qwe854896/q1/Makefile
- hw2/qwe854896/q1/main.cpp
- hw2/qwe854896/q2/Makefile
- hw2/qwe854896/q2/_vector.cpp
- hw2/qwe854896/q2/test_vector.py
> qwe854896 hw2 attempt1

- hw2/tychuang1211/q1/Makefile
- hw2/tychuang1211/q1/line.hpp
- hw2/tychuang1211/q1/main.cpp
- hw2/tychuang1211/q2/Makefile
- hw2/tychuang1211/q2/libvector.cpp
- hw2/tychuang1211/q2/test_vector.py
> tychuang1211 hw2 attempt1

- hw2/looksgreat/q1/line.cpp
- hw2/looksgreat/q1/line.hpp
- hw2/looksgreat/q1/makefile
- hw2/looksgreat/q2/cal.cpp
- hw2/looksgreat/q2/makefile
- hw2/looksgreat/q2/test_cal.py
> looksgreat hw2 attempt

- hw2/SmallHanley/q1/.clang-format
- hw2/SmallHanley/q1/Makefile
- hw2/SmallHanley/q1/q1.cpp
- hw2/SmallHanley/q2/Makefile
- hw2/SmallHanley/q2/_vector.cpp
- hw2/SmallHanley/q2/test_cal_rad.py
> SmallHanley hw2 attempt1

- hw2/jamie212/q1/makefile
- hw2/jamie212/q1/myLine.cpp
- hw2/jamie212/q2/makefile
- hw2/jamie212/q2/test_vector_angle.py
- hw2/jamie212/q2/vector_angle.cpp
> jamie212 hw2 attempt1

- hw2/ksh2027/q1/Line.cpp
- hw2/ksh2027/q1/Line.hpp
- hw2/ksh2027/q1/main.cpp
- hw2/ksh2027/q1/makefile
- hw2/ksh2027/q2/cal_angle.cpp
- hw2/ksh2027/q2/cal_angle_test.py
- hw2/ksh2027/q2/makefile
> hw2 submit by ksh2027

- hw2/henry0928/q1/Makefile
- hw2/henry0928/q1/line.cpp
- hw2/henry0928/q2/Makefile
- hw2/henry0928/q2/_vector.cpp
- hw2/henry0928/q2/test_.py
> henry0928-hw2-attempt2

- hw2/darrenleeleelee1/q1/line.cpp
- hw2/darrenleeleelee1/q1/makefile
- hw2/darrenleeleelee1/q2/angle.cpp
- hw2/darrenleeleelee1/q2/makefile
- hw2/darrenleeleelee1/q2/test_angle.py
> hw2 submit by darrenleeleelee1

- project/README.rst
- project/qwe854896/README.rst
> qwe854896-proposal-submission

- project/README.rst
- project/Yojahuang/README.md
> Yojahuang final project proposal

- project/README.rst
- project/looksgreat/README.rst
> looksgreat project proposal

- project/README.rst
- project/SmallHanley/README.md
> SmallHanley-proposal-submission

- hw3/jamie212/Makefile
- hw3/jamie212/_matrix.cpp
- hw3/jamie212/performance.py
- hw3/jamie212/performance.txt
- hw3/jamie212/test_matrix.py
> jamie212 hw3 attempt1

- hw3/mmi366127/Makefile
- hw3/mmi366127/_matrix.cpp
- hw3/mmi366127/performance.txt
- hw3/mmi366127/test_matrix.py
> mmi366127-hw3-attempt2

- hw3/mmi366127/Makefile
- hw3/mmi366127/_matrix.cpp
- hw3/mmi366127/test_matrix.py
> mmi366127-hw3 first attempt.

- hw3/huroy5518/Makefile
- hw3/huroy5518/matrix.cpp
- hw3/huroy5518/performance.txt
- hw3/huroy5518/test/test_matrix.py
- hw3/huroy5518/test/test_mul.py
- hw3/huroy5518/test/test_performance.py
> huroy5518 HW3 Attempt 1

- hw3/Yojahuang/.gitignore
- hw3/Yojahuang/Makefile
- hw3/Yojahuang/includes/TileHelper.h
- hw3/Yojahuang/includes/matrix.h
- hw3/Yojahuang/matrix_mul.cpp
- hw3/Yojahuang/performance.py
- hw3/Yojahuang/performance.txt
- hw3/Yojahuang/srcs/TileHelper.cpp
- hw3/Yojahuang/srcs/matrix.cpp
- hw3/Yojahuang/test_matrix_mul.py
> Yojahuang hw3 attempt1

- hw3/SmallHanley/Makefile
- hw3/SmallHanley/Matrix.h
- hw3/SmallHanley/_matrix.cpp
- hw3/SmallHanley/perf.py
- hw3/SmallHanley/test_matrix.py
> Smallhanley hw3 attempt1

- hw3/henry0928/_matrix.cpp
- hw3/henry0928/makefile
- hw3/henry0928/performance.py
- hw3/henry0928/performance.txt
- hw3/henry0928/test_.py
> henry0928-hw3-attempt3

- hw3/yoyojs200602/.gitignore
- hw3/yoyojs200602/Makefile
- hw3/yoyojs200602/_matrix.cpp
- hw3/yoyojs200602/perfomance.py
- hw3/yoyojs200602/performance.txt
- hw3/yoyojs200602/test_multiply.py
- hw3/yoyojs200602/validate.py
> initial commit

- hw3/darrenleeleelee1/Makefile
- hw3/darrenleeleelee1/inc/matrix.hpp
- hw3/darrenleeleelee1/inc/matrix_multiply.hpp
- hw3/darrenleeleelee1/performance.txt
- hw3/darrenleeleelee1/src/_matrix.cpp
- hw3/darrenleeleelee1/test/test_matrix.py
- hw3/darrenleeleelee1/test/test_matrixMultiply.py
> hw3 submit by darrenleeleelee1

- project/README.rst
- project/XDEv11/README.md
> XDEv11-proposal

- project/README.rst
- project/ksh2027/README.rst
> ksh2027-proposal-submission

- project/BillyNI-OUO/README.rst
- project/README.rst
> BillyNI-OUO project proposal submission

- project/README.rst
- project/jamie212/README.md
> jamie212 project submission attempt 1

- project/README.rst
- project/tychuang1211/README.md
> tychuang1211 proposal submission

- hw4/huroy5518/Makefile
- hw4/huroy5518/matrix.cpp
> huroy5518 hw4 attempt1

- hw4/mmi366127/Makefile
- hw4/mmi366127/_matrix.cpp
- hw4/mmi366127/test_matrix.py
> mmi366127-hw4-attempt1

- hw4/qwe854896/Makefile
- hw4/qwe854896/include/CustomAllocator.h
- hw4/qwe854896/include/Matrix.h
- hw4/qwe854896/include/Multiply.h
- hw4/qwe854896/src/CustomAllocator.cpp
- hw4/qwe854896/src/Matrix.cpp
- hw4/qwe854896/src/Multiply.cpp
- hw4/qwe854896/src/_matrix.cpp
- hw4/qwe854896/test/test_Matrix.py
- hw4/qwe854896/test/test_Multiply.py
- hw4/qwe854896/test/test_benchmark.py
> qwe854896 hw4 attempt1

- hw4/tychuang1211/Makefile
- hw4/tychuang1211/matrix.cpp
- hw4/tychuang1211/matrix.hpp
- hw4/tychuang1211/test_matrix.py
> Tychuang1211 hw4 attempt1

- hw4/looksgreat/makefile
- hw4/looksgreat/matrix.cpp
> Looksgreat hw4 attempt

- hw4/luuun1216/Allocator.hpp
- hw4/luuun1216/Makefile
- hw4/luuun1216/_matrix.cpp
> luuun1216 hw4 attempt1

- hw4/BillyNI-OUO/Makefile
- hw4/BillyNI-OUO/matrix.cpp
- hw4/BillyNI-OUO/matrix_test.py
> BillyNI-OUO hw4 attempt1 

- hw4/ksh2027/alloc.cpp
- hw4/ksh2027/makefile
- hw4/ksh2027/matrix.cpp
> hw4 submit by ksh2027

- hw4/henry0928/_matrix.cpp
- hw4/henry0928/makefile
> henry0928-hw4-attemp1

- hw4/Calvin9c/Makefile
- hw4/Calvin9c/_matrix.cpp
- hw4/Calvin9c/allocator.hpp
> Calvin9c-hw4-attempt1

- hw3/ksh2027/makefile
- hw3/ksh2027/matrix.cpp
- hw3/ksh2027/performance.txt
- hw3/ksh2027/test_matrix.py
> hw3 submit by ksh2027

- hw1/Calvin9c/countline.py
- hw1/Calvin9c/countline.sh
> Calvin9c hw1 attempt3

- hw5/huroy5518/Makefile
- hw5/huroy5518/matrix.hpp
> huroy5518 hw5 attempt1

- hw5/mmi366127/Makefile
- hw5/mmi366127/matrix.hpp
- hw5/mmi366127/test_matrix.py
> mmi366127-hw5-attempt1

- hw5/qwe854896/Makefile
- hw5/qwe854896/include/CustomAllocator.h
- hw5/qwe854896/include/Matrix.h
- hw5/qwe854896/include/Multiply.h
- hw5/qwe854896/include/matrix.hpp
- hw5/qwe854896/src/CustomAllocator.cpp
- hw5/qwe854896/src/Matrix.cpp
- hw5/qwe854896/src/Multiply.cpp
- hw5/qwe854896/test/test_Matrix.py
- hw5/qwe854896/test/test_Multiply.py
- hw5/qwe854896/test/test_benchmark.py
> qwe854896 hw5 attempt1

- hw5/XDEv11/Makefile
- hw5/XDEv11/matrix.hpp
> XDEv11-hw5

- hw5/looksgreat/Makefile
- hw5/looksgreat/matrix.hpp
> Looksgreat hw5 attempt2

- hw5/jamie212/Makefile
- hw5/jamie212/matrix.hpp
> Jamie212 hw5 attempt1

- hw5/SmallHanley/Makefile
- hw5/SmallHanley/matrix.hpp
> SmallHanley-hw5-attempt1

- hw5/luuun1216/Makefile
- hw5/luuun1216/matrix.hpp
> luuun1216 hw5 attempt1

- hw5/henry0928/Makefile
- hw5/henry0928/matrix.hpp
> henry0928-hw5-attempt5

- hw5/B10732009/.clang-format
- hw5/B10732009/.gitignore
- hw5/B10732009/makefile
- hw5/B10732009/matrix.cpp
- hw5/B10732009/matrix.hpp
> B10732009 hw5 attempt1

- hw5/Calvin9c/Makefile
- hw5/Calvin9c/matrix.hpp
> Calvin9c hw5 attempt1

- hw5/darrenleeleelee1/Makefile
- hw5/darrenleeleelee1/inc/matrix.hpp
- hw5/darrenleeleelee1/inc/matrix_multiply.hpp
- hw5/darrenleeleelee1/performance.txt
- hw5/darrenleeleelee1/src/_matrix.cpp
- hw5/darrenleeleelee1/src/mod.cpp
- hw5/darrenleeleelee1/test/test_matrix.py
- hw5/darrenleeleelee1/test/test_matrixMultiply.py
> darrenleeleelee1 hw5 attempt1

- hw6/huroy5518/Makefile
- hw6/huroy5518/matrix.cpp
> huroy5518 hw6 attempt 1

- hw6/mmi366127/Makefile
- hw6/mmi366127/matrix.hpp
- hw6/mmi366127/mod.cpp
- hw6/mmi366127/test_matrix.py
> Mmi366127 hw6 attempt1

- hw6/qwe854896/Makefile
- hw6/qwe854896/include/CustomAllocator.h
- hw6/qwe854896/include/Matrix.h
- hw6/qwe854896/include/Multiply.h
- hw6/qwe854896/include/matrix.hpp
- hw6/qwe854896/src/CustomAllocator.cpp
- hw6/qwe854896/src/Matrix.cpp
- hw6/qwe854896/src/Multiply.cpp
- hw6/qwe854896/src/_matrix.cpp
- hw6/qwe854896/src/mod.cpp
> qwe854896 hw6 attempt1

- hw6/looksgreat/makefile
- hw6/looksgreat/matrix.cpp
> Looksgreat hw6 attempt1

- hw6/SmallHanley/Makefile
- hw6/SmallHanley/Matrix.h
- hw6/SmallHanley/_matrix.cpp
> SmallHanley-hw6-attempt1

- hw6/luuun1216/Makefile
- hw6/luuun1216/_matrix.cpp
> luuun1216 hw6 attempt1

- hw6/BillyNI-OUO/Makefile
- hw6/BillyNI-OUO/matrix.cpp
> BillyNI-OUO-hw6-attempt1

- hw6/ksh2027/makefile
- hw6/ksh2027/matrix.cpp
> hw6 submit by ksh2027

- hw6/henry0928/_matrix.cpp
- hw6/henry0928/makefile
> henry0928-hw6-attempt1

- hw6/B10732009/.clang-format
- hw6/B10732009/.gitignore
- hw6/B10732009/_matrix.cpp
- hw6/B10732009/_matrix.hpp
- hw6/B10732009/makefile
> B10732009 hw6 attempt1

- hw6/Calvin9c/Makefile
- hw6/Calvin9c/_matrix.cpp
> Calvin9c-hw6-attempt2

- hw6/darrenleeleelee1/Makefile
- hw6/darrenleeleelee1/_matrix.cpp
- hw6/darrenleeleelee1/inc/matrix.hpp
- hw6/darrenleeleelee1/inc/matrix_multiply.hpp
- hw6/darrenleeleelee1/performance.txt
- hw6/darrenleeleelee1/src/_matrix.cpp
- hw6/darrenleeleelee1/test/test_matrix.py
- hw6/darrenleeleelee1/test/test_matrixMultiply.py
> darrenleeleelee1 hw6 attemp1
